export const styles = {
    container: {
      maxWidth: 600,
      margin: "2rem auto",
      padding: 20,
      boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
      borderRadius: 10,
      fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    },
    form: {
      display: "flex",
      gap: 10,
      marginBottom: 20,
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "center",
    },
    input: {
      flexGrow: 1,
      padding: 10,
      fontSize: 16,
      borderRadius: 6,
      border: "1px solid #ccc",
    },
    select: {
      padding: 10,
      fontSize: 16,
      borderRadius: 6,
      border: "1px solid #ccc",
    },
    button: {
      padding: "10px 20px",
      backgroundColor: "#007bff",
      border: "none",
      borderRadius: 6,
      color: "#fff",
      cursor: "pointer",
    },
    cancelButton: {
      padding: "10px 20px",
      backgroundColor: "#6c757d",
      border: "none",
      borderRadius: 6,
      color: "#fff",
      cursor: "pointer",
    },
    taskList: {
      listStyle: "none",
      padding: 0,
      margin: 0,
    },
    taskItem: {
      border: "1px solid #ddd",
      padding: 15,
      marginBottom: 10,
      borderRadius: 8,
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    taskActions: {
      display: "flex",
      gap: 10,
    },
    actionButton: {
      padding: "6px 12px",
      border: "none",
      borderRadius: 6,
      color: "#fff",
      cursor: "pointer",
      backgroundColor: "#007bff",
    },
  };
  